name: Test, release and publish

on:
  push:
    branches:
      - main

jobs:
  test:
    uses: ./.github/workflows/test.yaml
  release:
    uses: ./.github/workflows/release.yaml
  publish:
    uses: ./.github/workflows/publish.yaml
